
server.port= 8080
ollama.url= http://localhost:11434

mcp.server.url= http://localhost:3001
elastic.url=  http://localhost:9200
#https://YOUR_ELASTIC_URL
elastic.api-key= YOUR_ELASTIC_API_KEY

gemini.api.key=YOUR_GEMINI_API_KEY

spring.kafka.bootstrap-servers= localhost:9092

spring.application.name=AdaptiveAgentApplication
